services:
  db:
    image: mysql:latest
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: master_user
      MYSQL_PASSWORD: best_password
    ports:
      - "3306:3306"   # expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql         # persistent storage for MySQL data

volumes:
  db_data: