import "~/styles/globals.css";

import { type Metadata } from "next";
import { Raleway } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Track Record",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${raleway.variable}`}>
      <body>
        <TRPCReactProvider>
          <Header/>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
//Yandro was here;,l.